// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "@/lib/supabaseClient";

const lovableAuth = createLovableAuth({});

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple",
      opts?: { redirect_uri?: string; scopes?: string[] }
    ) => {
      // Build extra params with Gmail scopes for Google provider
      const extraParams: Record<string, string> = {};
      if (provider === "google" && opts?.scopes) {
        extraParams.scope = opts.scopes.join(" ");
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: Object.keys(extraParams).length > 0 ? extraParams : undefined,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
